LINK.o = $(LINK.cc)
SHELL := /bin/bash

outputonly_executable = print-int assert assert-ex assert-info

input_output_executable = permission-all permission-define permission date

error_executables = assert-ex

include ../programmingbook.mk

