outputonly_executable = 2d-no-length 2d-array-fill \
print-matrix-size sum-array-range-for

# compare-matrix-address print-array-address-exp print-array-address print-matrix-address-level print-matrix-address 

input_output_executable = sum-array sum-array-range-for \
match inner-product fib-array prime-array prime-array-line bubble-sort \
matrix-multiply matrix-multiply-lines \
life mirror circle ttt 

error_executable = assert-array

figure_files = 2d-array-address.pdf
include ../programmingbook.mk
