outputonly_executable = 

input_output_executable = sys-function cin-count leap-year-function leap-year-forward leap-year-repeat print-digits year-month print-start-end multi-io-message scanf-nonspace  year-month-default   multi-dim-array-parameter calc compare match-function ttt life mirror function-parameter multi-io partial-inc print-array-with-function print-matrix-address-message print-array-with-function

sys-function: sys-function.o
	g++ sys-function.o -o sys-function -lm

include ../programmingbook.mk





