outputonly_executable = short-long static-foo non-static-foo cpp11-int cpp11-unsigned-int

# auto-array-pointer

input_output_executable = short-long-io pi square square-updatei array-sum size-of-long size-of-uint32

include ../programmingbook.mk
