int strlen(char *string);
char *strcpy(char *dest, char *source);
char *strcat(char *dest, char *source);
char *strncpy(char *dest, char *source, int i);
char *strncat(char *dest, char *source, int i);
int strcmp(char *str1, char *str2);
int strncmp(char *str1, char *str2, int n);
char *strchr(char *string, int c);
char *strrchr(char *string, int c);
char *strspn(char *string, char *chars);
char *strcspn(char *string, char *chars);
char *strstr(char *string1, char *string2);
char *strtok(char *string, char *delimeters);
