outputonly_executable = string-empty-clear \
c-string-size c-string-init c-string-output

input_output_executable = string-io string-eof string-eof-func \
string-getline string-getline-eof string-2-getline \
string-length string-copy string-concat \
string-reverse string-sort string-match find parse-path \
c-string-io c-string-getline c-string-2-getline \
basic 

error_executable = string-reverse-wrong

include ../programmingbook.mk
