outputonly_executable = nine

input_output_executable = continue do-while for-print gcd no-continue not-less-than prime-break prime-flag prime sum-square-cubic-do-while sum-square-cubic sum divide-for eleven-for eof

include ../programmingbook.mk


