CXX = g++
LINK.o = $(LINK.cc)

outputonly_executable = struct-field-assign struct-init  \
struct-field-pointer struct-size struct-align \
struct-in-struct use-header 

input_output_executable = rational-val rational-pointer rational-ref rational-header \
ttt life mirror circle ones \
basic

include ../programmingbook.mk

