outputonly_executable = strange-logic 

input_output_executable = set-i-j swap multiple-assign set-i-j-sum set-i-j-divide set-i-j-mod  \
two-digit negative sizeof-int set-arith-order print-bool leap-year short-circuit no-short-circuit change change-mod identicalroot triangle

include ../programmingbook.mk


