outputonly_executable =

input_output_executable = if-then product-positive abs max-3 sort-print leap-year-else-if switch-power switch-power-no-break month calc-switch calc-switch-define compare-switch bad-leap-year-else-if cond-max-3 area-branch area-cond

include ../programmingbook.mk








