outputonly_executable = char-size ascii ascii-int ascii-dec char-assignment-int toupper

input_output_executable =  char-io  ascii-dec  char-overflow char-io char-io-get char-get-eof char-get-eof-func char-eof ctype-class

include ../programmingbook.mk





