outputonly_executable = ptr-size array-pointer-wrong array-pointer

input_output_executable = swap-by-pointer inc-with-array-index  \
first-positive

# address arith array-pointer inc3-with-pointer init-assign pointer-parameter

error_executable = sement-fault array-pointer-wrong

include ../programmingbook.mk
